services:
  - type: web
    name: kinnect
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile.backend
    envVars:
      - key: NODE_ENV
        value: production
      - key: DOCKER_BUILDKIT
        value: "1"
